Refactor
open-contracting-extensions/ocds_1_2_draft_extension pull request #1
Opened 2023-05-29 23:59 UTC by duncandewhurst

For background, see https://github.com/open-contracting/ocds-extensions/issues/201 and [Slack discussion](https://opencontractingint.slack.com/archives/C03S8JL100P/p1681773662849569?thread_ts=1661872262.757289&cid=C03S8JL100P).

2023-06-02 09:46 UTC, odscjen requested changes
There's no change log at the bottom of the README.md, should there be to reference the removal of `identifiers` and `exclusionGrounds`?

2023-06-02 09:46 UTC, odscjen commented on README.md
>  For correspondences to eForms fields, see OCDS for eForms.
```suggestion
For correspondences to eForms fields, see [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/en/).
```
I know the link is already in the first section but for completeness it feels like it should be repeated here

2023-06-07 05:04 UTC, duncandewhurst commented
> There's no change log at the bottom of the README.md, should there be to reference the removal of `identifiers` and `exclusionGrounds`?

I don't think so as we're still authoring the initial version of the extension.

2023-06-08 18:55 UTC, jpmckinney approved these changes

2023-06-08 19:00 UTC, jpmckinney commented
Do you remember why we split out simple identifier into its own extension? I can't remember now.

I think maybe we wanted to reuse the SimpleIdentifier definition in other extensions, but I can't remember which.

2023-06-08 19:48 UTC, duncandewhurst commented
It was so that the lots extension could depend on it without needing to depend on the whole of the 1.2 draft extension: https://github.com/open-contracting-extensions/ocds_lots_extension/pull/41#discussion_r1160273306

2023-06-08 19:49 UTC, duncandewhurst commented
Happy for this to be merged?

2023-06-08 20:00 UTC, jpmckinney commented
> It was so that the lots extension could depend on it without needing to depend on the whole of the 1.2 draft extension: https://github.com/open-contracting-extensions/ocds_lots_extension/pull/41#discussion_r1160273306

Oh, right – but later, we learned that all dependencies need to be explicitly declared in `extensions` arrays, because the Data Review Tool and other tools don't apply dependencies on their own.

So, in the end, we added SimpleIdentifier directly to the lots extension, since the changes to lots was breaking existing publications.

As such, we maybe don't want to remove these from this extension, and we can delete the identifiers extension (and merge back its updates into this extension).

It's a bit of a run-around, but at least we learned/reminded ourselves of how dependencies work.

2023-06-08 20:03 UTC, duncandewhurst commented
All good :-) I'll tackle those changes next week.

2023-06-19 03:26 UTC, closed without merging

2023-06-19 03:50 UTC, duncandewhurst commented
@jpmckinney I've archived https://github.com/open-contracting-extensions/ocds_tender_contract_identifiers_extension. I don't have permission to delete it.

2023-06-19 15:01 UTC, jpmckinney commented
Thanks - I've removed it from the extension registry as well.