Merge changes
open-contracting-extensions/ocds_1_2_draft_extension pull request #2
Opened 2023-06-19 03:49 UTC by duncandewhurst

Follow up to https://github.com/open-contracting-extensions/ocds_1_2_draft_extension/pull/1#issuecomment-1583262266, merge changes from https://github.com/open-contracting-extensions/ocds_tender_contract_identifiers_extension and https://github.com/open-contracting-extensions/ocds_1_2_draft_extension/pull/1

2023-06-19 15:22 UTC, odscjen requested changes

2023-06-19 15:22 UTC, odscjen commented on release-schema.json
> +          "description": "The list, register or system from which the identifier is taken. If the scope of the list, register or system from which the identifier is drawn is national, it is suggested
```suggestion
          "description": "The list, register or system from which the identifier is taken. If the scope of the list, register or system is national, it is suggested to follow the pattern {​ISO 3166-1 alpha-2}-{​system}. If it is subnational, it is suggested to follow the pattern {​ISO 3166-2}-{​system}.",
```
Just feels like some unnecessary repetition

2023-06-26 23:20 UTC, jpmckinney commented on README.md
> +
```suggestion

**Only use this extension with the OCDS for eForms profile.**

```

2023-06-26 23:20 UTC, jpmckinney commented on codelists/+partyRole.csv
> +wholesaleBuyer,Wholesale buyer,"A buyer (e.g. a central purchasing body) buying goods, works or services intended for other buyers. Organisations with this role should not have the buyer role."
Let's omit the second sentence for now. I'm hoping Jáchym can clarify why he thought it was important to include in https://github.com/open-contracting/standard/issues/1180

```suggestion
wholesaleBuyer,Wholesale buyer,"A buyer (e.g. a central purchasing body) buying goods, services or works intended for other buyers."
```

2023-06-30 17:46 UTC, jpmckinney approved these changes

2023-06-30 17:46 UTC, merged